### ISSUE TITLE
Can we please get a version packaged for dotnet core 3.1?

### ISSUE THREAD

**Issue by carelschoeman** [jonstodle/DotnetVersion#10]
Currently I'm trying to create a build pipeline for a dotnet core 3.1 and would really like to use this tool but it fails since the nuget package still seems to target 2.1. I saw that the current state of the project already targets 3.1, not sure if it's simply just a case of rebuilding and packaging or if the pipeline should be updated (I saw a reference to 2.2.401).

The error I'm getting:
Step 17/28 : RUN dotnet version -p redacted.csproj --no-git --new-version $BUILD_VERSION
 ---> Running in f5ab2397b6d1
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.1.5 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.1.0&arch=x64&rid=debian.10-x64

And the tools directory (from a docker container):
root@2a3f48f9f7cf:~/.dotnet/tools/.store/dotnetversion/1.5.0/dotnetversion/1.5.0/tools# ls
netcoreapp2.1

**Comment by VictorioBerra** [comment]
Im having the same problem. Would compiling this as a self-contained EXE where it comes with the runtime fix this? @jonstodle

**Comment by VictorioBerra** [comment]
If anyone needs this to work on an Windows Azure DevOps build agent, you can do the following:

```yaml
    - powershell: |
        iwr https://dot.net/v1/dotnet-install.ps1 -outfile dotnet-install.ps1
        .\dotnet-install.ps1 -Channel 2.1 -Runtime dotnet -NoPath -InstallDir "C:\Program Files\dotnet"
      displayName: "Install 2.1.30 for dotnet-version dotnet tool"
```

This will install the dotnet 2.1.x runtime into the global folder `"C:\Program Files\dotnet"` where it will be picked up when `dotnet version` is ran. This will also NOT change the path so your other CLI commands and dotnet commands run using the latest dotnet as usual.
